services:
  # tempo-key-server
  tempo-key-server:
      platform: linux/x86_64
      hostname: 'tempo-key-server'
      build: .
      restart: always
      volumes:
      - './data/tempo-key-server-mysql-data:/var/lib/mysql'
      ports:
      - 8080:8080
      environment:
        NODE_ENV: development
        HTTP_PORT: 8080
        DATABASE_FILENAME: './data/database.sqlite'
        KNEX_DB_CONNECTION: '{"port":"3306","host":"127.0.0.1","database":"tempo-key-server","user":"","password":""}'
        KNEX_DB_CLIENT: sqlite3
        MIGRATE_KEY: my-grate-key
        SERVER_PRIVATE_KEY: '6dcc124be5f382be631d49ba12f61adbce33a5ac14f6ddee12de25272f943f8b'
        HOSTING_DOMAIN: 'http://localhost:8080'
